# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: BuildAndTest

on:
  push:
  pull_request:
    types: [opened]

jobs:
  build:

    runs-on: macos-13

    steps:
      
    - name: Checkout Repository
      uses: actions/checkout@v3
      
    - name: Update Xcode Settings
      run: |
        set -euo pipefail
        defaults write com.apple.dt.Xcode IDESkipPackagePluginFingerprintValidatation -bool YES
        defaults write com.apple.dt.Xcode IDESkipMacroFingerprintValidation -bool YES
      
    - name: Load Latest Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
        
    - name: Clean project
      run: swift package clean

    - name: Build project
      run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild build-for-testing -destination 'name=iPhone 14 Pro' -scheme 'Bunny-Package' -skipPackagePluginValidation | xcpretty

    - name: Run tests
      run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild test-without-building -destination 'name=iPhone 14 Pro' -scheme 'Bunny-Package' -skipPackagePluginValidation | xcpretty
