# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Generate and Deploy Documentation

on:
  push:
    branches:
      - main
      - develop
      - feature/documentation

jobs:
  build-and-deploy:
    runs-on: macos-13
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      
    - name: Update Xcode Settings
      run: |
        set -euo pipefail
        defaults write com.apple.dt.Xcode IDESkipPackagePluginFingerprintValidatation -bool YES
      
    - name: Load Latest Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    
    - name: Install SourceDocs
      run: brew install sourcedocs
      
    - name: Build project
      run: swift build
    
    - name: Generate Documentation
      run: sourcedocs generate --all-modules

    - name: Process Documentation
      run: |
        # Make the script executable
        chmod +x ./fix_readme.sh
        # Run the script
        ./fix_readme.sh

    - name: Commit Documentation
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update documentation"
    
    - name: Push Changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref_name }}
        force: true
